DATA_PATH = "Data"
TRAIN_DATASET_PATH = "Data/train"
TEST_DATASET_PATH = "Data/test"
VALID_DATASET_PATH = "Data/valid"
DATA_AUGMENTED_PATH = "Data/augmented"
DATA_AUGMENTED_IMAGES_PATH = "Data/augmented/images"
DATA_AUGMENTED_ANNOTED_PATH = "Data/augmented/annoted"
DATA_AUGMENTED_LABELS_PATH = "Data/augmented/labels"